### ISSUE TITLE
Add PHP_ENABLE_XDEBUG env var

### ISSUE THREAD

**Issue by bonndan** [ulsmith/alpine-apache-php7#1]
Hi!

Nice image! If I understand correctly, xdebug is always enabled in the image with full-blown features. Could you wrap the start.sh section in an if clause so that xdebug depends on an env var like PHP_ENABLE_XDEBUG? What do you think?

**Comment by smiffy6969** [comment]
Yeah, sorry about the delay, life has been getting in the way lately!

XDebug can be a PITA, I totally need this too, how many times I have had to go and add overrides so I can see my debug, man I do love a raw debug, showing my age.

With that in mind, just for you, it is now disabled by default (as it was only added to allow unit testing) and to enable it you have to add the ENV PHP_XDEBUG_ENABLED=true.... remove the line to turn it off.
