### ISSUE TITLE
Can't create directory '/run/apache2': File exists

### ISSUE THREAD

**Issue by isbkch** [ulsmith/alpine-apache-php7#6]
Getting the error `mkdir: can't create directory '/run/apache2': File exists` when building from the image source.

Created PR: https://github.com/ulsmith/alpine-apache-php7/pull/7

**Comment by Royalxm** [comment]
thx for the pull work for me 

author move your :+1:

**Comment by Royalxm** [comment]
Nice author and thx for this projet

**Comment by smiffy6969** [comment]
my bad... been a rough year... did notice was waiting. Rebuilt on DH too
